
function h0=DataLog(StrDati,Title,nfig)

% BackColor=['c','w'];
BackColor=[[0.6 0.8 1.0];[0.941 0.941 0.941]];
h0=figure(nfig);
set(h0, 'Units', 'normalized', 'Position', [0.5 0 0.35 0.65]);
xpos=[0.02,0.20];
ypos=0.86;

uicontrol('Parent',h0, ...
        'Units','normalized', ...
        'FontSize',9, ...
        'Style','text',...
        'Position', [0.02 0.9 0.90 0.04],...
        'BackgroundColor','w', ...
        'String',Title);

for i=1:size(StrDati,2)
    for ii=1:size(StrDati,1)

        uicontrol('Parent',h0, ...
                'Units','normalized', ...
                'FontSize',9, ...
                'Style','text', ...
                'Position', [xpos(ii) ypos 0.15 0.026], ...
                'BackgroundColor',BackColor(ii,:), ...
                'String',StrDati(ii,i));
    end
    ypos=ypos-0.03;
end
